In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set(style='darkgrid')
#import warnings
#warnings.filterwarnings('ignore')

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving train.csv to train.csv


In [ ]:
data = pd.read_csv(r'train.csv',encoding='latin1',on_bad_lines='skip',lineterminator='\n')

In [ ]:
data.head()

id                                       comment_text toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...     0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...     0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...     0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...     0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...     0   

  severe_toxic obscene threat insult identity_hate  
0            0       0      0      0             0  
1            0       0      0      0             0  
2            0       0      0      0             0  
3            0       0      0      0             0  
4            0       0      0      0             0

In [ ]:
data.shape

(163629, 8)

In [ ]:
data_2 = data.copy()

In [ ]:
#Dropping Null Values
data_3 = data_2.dropna()

In [ ]:
data_3

id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
163624  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
163625  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
163626  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
163627  fff125370e4aaaf3  And it looks like it was actually you who put ...   
163628  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

       toxic severe_toxic obscene threat insult identity_hate  
0          0            0       0      0      0             0  
1          0            0       0      0      0             0  
2          0            0       0      0      0             0  
3          0            0       0      0      0             0  
4          0            0       0      0      0             0  
...      ...          ...     ...    ...    ...           ...  
163624     0            0       0      0      0             0  
163625     0            0       0      0      0             0  
163626     0            0       0      0      0             0  
163627     0            0       0      0      0             0  
163628     0            0       0      0      0             0  

[158282 rows x 8 columns]

In [ ]:
data_3[data_3['toxic'].isin(['0', '1']) == False]

id  \
12      Thanks for uploading Image:Wonju.jpg. I notice...   
137     = My Famous Article ==witze  happiness  wikip...   
8815                                        Len Metherell   
12905   It seems that people are using this page to pr...   
13246    Twitter and Wikia usually are not reliable so...   
16841                 As there are Spaniards in the movie   
29918                                           Next time   
38401              I see that you already have an archive   
40902   9. """"It is also a clear fact that the system...   
43374                                       In my opinion   
49555   I have tried to fix the refs from your descrip...   
49556                                      Re. the figure   
62696   Are you quite sure that _àshould be sorted und...   
68824                                       In my opinion   
75307                                    c415e3024ca37ba4   
88227                                          Sorry John   
117191  Thanks for uploading Image:Chyr.jpg. I noticed...   
123902  There was no evidence whatever that a superman...   
126740  'Get off your high horse' seems like an insult...   
140000  Thank you for your copy edits and reference wo...   
140985  Oh crap! did I type that? I think I had a bit ...   
152988  Indeed people have written about the sound of ...   
157447  Isn't a photo of a muzzled dog more relevant t...   
160881                                   d5af077462f356d7   

                                             comment_text  \
12       so the copyright status is unclear. If you di...   
137                                    regardless of race   
8815                           who made his debut in 1930   
12905                               or own obscure tastes   
13246                               especially the latter   
16841    it's sure that the movie doesn't take place b...   
29918    type """"http://en.wikipedia.org/wiki/"""" on...   
38401               therefore you can just edit this page   
40902                                        be the guard   
43374         the accuracy of the content depends on fact   
49555               but considering most of it is correct   
49556                                                well   
62696               and is sorted separately in Danish (a   
68824         the accuracy of the content depends on fact   
75307   "\n\n mgts \n\nNext generation wireless networ...   
88227                              its just a tribute act   
117191   so the copyright status is unclear. If you di...   
123902                                      brought a son   
126740   and people have easily been blocked for doing...   
140000                                      by your edits   
140985   since I been at wikipedia this notion of a ""...   
152988              and jewel makers such as Sharon Alouf   
157447                          such as some public parks   
160881  ":::* I'm not using jabs or insults of any kin...   

                                                    toxic  \
12       then you will need to specify the owner of th...   
137                                                   age   
8815     see 6th Edition The Encyclopedia of AFL Footb...   
12905    which they find """"super."""" I agree with t...   
13246                       like Wikipedia. As I had said   
16841    you can't guarantee what is the exact year. T...   
29918    then type """"User:Esskater11/*USERBOX NAME*"...   
38401                 cut out the bit you want to archive   
40902                                              stance   
43374               not on how the station markets itself   
49555    it might be easier to work from that. If you ...   
49556    this is the problem I've been trying to descr...   
62696                                                   b   
68824               not on how the station markets itself   
75307    multi-protocol programmable test system that ...   
88227    yes Gilmour had th

In [ ]:
data_4 = data_3.drop(data_3[data_3['toxic'].isin(['0', '1']) == False].index, axis=0)
data_4

id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
163624  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
163625  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
163626  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
163627  fff125370e4aaaf3  And it looks like it was actually you who put ...   
163628  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

       toxic severe_toxic obscene threat insult identity_hate  
0          0            0       0      0      0             0  
1          0            0       0      0      0             0  
2          0            0       0      0      0             0  
3          0            0       0      0      0             0  
4          0            0       0      0      0             0  
...      ...          ...     ...    ...    ...           ...  
163624     0            0       0      0      0             0  
163625     0            0       0      0      0             0  
163626     0            0       0      0      0             0  
163627     0            0       0      0      0             0  
163628     0            0       0      0      0             0  

[158258 rows x 8 columns]

In [ ]:
data_4.shape

(158258, 8)

In [ ]:
print(f"First_id_length={len(data_4['id'][0])},Second_id_length={len(data_4['id'][1])},Third_id_length={len(data_4['id'][2])}")

First_id_length=16,Second_id_length=16,Third_id_length=16


In [ ]:
#pd.set_option('display.max_rows', None)
data_4[data_4['id'].str.len() != 16]

id  \
822                                                  Well   
1733    I can only assume because he is one of you and...   
2849                     ",0,0,0,0,0,0\n0777b13c678927d8"   
4597                     ",0,0,0,0,0,0\n0c08677a1fe3978f"   
5407                     ",0,0,0,0,0,0\n0e33caffde293a89"   
...                                                   ...   
157331                   ",0,0,0,0,0,0\n9c2ae5e27b1f7d83"   
160389              If you just go and include them again   
160882                   ",0,0,0,0,0,0\nd5be22851afa72e4"   
162539  @Powergate: I thought I said to remove yoursel...   
162664                   ",0,0,0,0,0,0\nf0e87d72d2889b83"   

                                             comment_text toxic severe_toxic  \
822                                            there was"     0            0   
1733                that guy (you? should be blocked. """     1            0   
2849    "First off, modern computer-generated ornate r...     0            0   
4597    "\n\n Request regarding current RfAr/Clarifica...     0            0   
5407    i just got on here a little while ago i am loo...     0            0   
...                                                   ...   ...          ...   
157331  Your Bondpedia has the potential to cover ever...     0            0   
160389                                      yes it does."     0            0   
160882  "\nThat's nearly there. It should be ""| last ...     0            0   
162539   it has been known to happen.  You aren't help...     0            0   
162664  RE: Your comments \n\nI am concerned about wha...     0            0   

       obscene threat insult identity_hate  
822          0      0      0             0  
1733         1      0      1             1  
2849         0      0      0             0  
4597         0      0      0             0  
5407         0      0      0             0  
...        ...    ...    ...           ...  
157331       0      0      0             0  
160389       0      0      0             0  
160882       0      0      0             0  
162539       0      0      0             0  
162664       0      0      0             0  

[180 rows x 8 columns]

In [ ]:
data_5 = data_4.copy()  # Create a copy if you want to keep the original DataFrame
data_5.drop(data_5[data_5['id'].str.len() != 16].index, axis=0, inplace=True)
data_5

id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
163624  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
163625  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
163626  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
163627  fff125370e4aaaf3  And it looks like it was actually you who put ...   
163628  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

       toxic severe_toxic obscene threat insult identity_hate  
0          0            0       0      0      0             0  
1          0            0       0      0      0             0  
2          0            0       0      0      0             0  
3          0            0       0      0      0             0  
4          0            0       0      0      0             0  
...      ...          ...     ...    ...    ...           ...  
163624     0            0       0      0      0             0  
163625     0            0       0      0      0             0  
163626     0            0       0      0      0             0  
163627     0            0       0      0      0             0  
163628     0            0       0      0      0             0  

[158078 rows x 8 columns]

In [ ]:
import re

def clean_text(text):
    text = text.lower()
    text = text.strip(' ') # Removing leading and trailing white spaces
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\n', ' ', text)
    text = re.sub('^[a-zA-Z]+',  " ",str(text))# Search for all non-letters,Replace all non-letters with spaces

    return text

In [ ]:
data_6 = data_5.copy()
data_6['comment_text'] = data_6['comment_text'].apply(lambda text : clean_text(text))

In [ ]:
data_6

id                                       comment_text  \
0       0000997932d777bf    why the edits made under my username hardcor...   
1       000103f0d9cfb60f    he matches this background colour im seeming...   
2       000113f07ec002fd    man im really not trying to edit war its jus...   
3       0001b41b1c6bb37e   more i cant make any real suggestions on impr...   
4       0001d958c54c6e35    sir are my hero any chance you remember what...   
...                  ...                                                ...   
163624  ffe987279560d7ff    for the second time of asking when your view...   
163625  ffea4adeee384e90    should be ashamed of yourself   that is a ho...   
163626  ffee36eab5c267c9      umm theres no actual article for prostitut...   
163627  fff125370e4aaaf3    it looks like it was actually you who put on...   
163628  fff46fc426af1f9a   and  i really dont think you understand  i ca...   

       toxic severe_toxic obscene threat insult identity_hate  
0          0            0       0      0      0             0  
1          0            0       0      0      0             0  
2          0            0       0      0      0             0  
3          0            0       0      0      0             0  
4          0            0       0      0      0             0  
...      ...          ...     ...    ...    ...           ...  
163624     0            0       0      0      0             0  
163625     0            0       0      0      0             0  
163626     0            0       0      0      0             0  
163627     0            0       0      0      0             0  
163628     0            0       0      0      0             0  

[158078 rows x 8 columns]

In [ ]:
# Replace 'toxic', 'severe_toxic', etc., with the actual column names you want to convert to int

columns_to_convert = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Convert selected columns to int
data_6[columns_to_convert] = data_6[columns_to_convert].astype(int)


In [ ]:
data_6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158078 entries, 0 to 163628
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype 
---  ------         --------------   ----- 
 0   id             158078 non-null  object
 1   comment_text   158078 non-null  object
 2   toxic          158078 non-null  int64 
 3   severe_toxic   158078 non-null  int64 
 4   obscene        158078 non-null  int64 
 5   threat         158078 non-null  int64 
 6   insult         158078 non-null  int64 
 7   identity_hate  158078 non-null  int64 
dtypes: int64(6), object(2)
memory usage: 10.9+ MB


In [ ]:
#Split the data
x = data_6['comment_text']
y = data_6.iloc[:,2:].values

In [ ]:
x

0           why the edits made under my username hardcor...
1           he matches this background colour im seeming...
2           man im really not trying to edit war its jus...
3          more i cant make any real suggestions on impr...
4           sir are my hero any chance you remember what...
                                ...                        
163624      for the second time of asking when your view...
163625      should be ashamed of yourself   that is a ho...
163626        umm theres no actual article for prostitut...
163627      it looks like it was actually you who put on...
163628     and  i really dont think you understand  i ca...
Name: comment_text, Length: 158078, dtype: object

In [ ]:
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
max_features = 100000

In [ ]:
import tensorflow as tf
import keras
from keras.layers import TextVectorization

In [ ]:
vectorizer = TextVectorization(max_tokens=max_features,
                               output_sequence_length=1800,
                               output_mode='int')

In [ ]:
vectorizer.adapt(x.values)

In [ ]:
vectorized_text = vectorizer(x.values)

In [ ]:
vectorized_text

<tf.Tensor: shape=(158078, 1800), dtype=int64, numpy=
array([[   81,     2,   122, ...,     0,     0,     0],
       [   54,  2460,    14, ...,     0,     0,     0],
       [  437,    73,   129, ...,     0,     0,     0],
       ...,
       [10807,   385,    52, ...,     0,     0,     0],
       [   12,   548,    49, ...,     0,     0,     0],
       [    5,     8,   129, ...,     0,     0,     0]])>

In [ ]:
import tensorflow as tf

#MCSHBAP - map, chache, shuffle, batch, prefetch  from_tensor_slices, list_file
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8) # helps bottlenecks

In [ ]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

<b><h1>MODEL BUILDING

**1.LSTM MODEL**

In [ ]:
from keras.models import Sequential
from keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [ ]:
model = Sequential()
# Create the embedding layer
model.add(Embedding(max_features+1, 32))
# Bidirectional LSTM Layer
model.add(Bidirectional(LSTM(32, activation='tanh')))
# Feature extractor Fully connected layers
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
# Final layer
model.add(Dense(6, activation='sigmoid'))

In [ ]:
model.compile(loss='BinaryCrossentropy', optimizer='Adam', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          3200032   
                                                                 
 bidirectional (Bidirection  (None, 64)                16640     
 al)                                                             
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [ ]:
history = model.fit(train, epochs=3, validation_data=val)

Epoch 1/3
6916/6916 [==============================] - 876s 126ms/step - loss: 0.0650 - accuracy: 0.9909 - val_loss: 0.0489 - val_accuracy: 0.9943
Epoch 2/3
6916/6916 [==============================] - 770s 111ms/step - loss: 0.0485 - accuracy: 0.9915 - val_loss: 0.0431 - val_accuracy: 0.9945
Epoch 3/3
6916/6916 [==============================] - 764s 110ms/step - loss: 0.0435 - accuracy: 0.9912 - val_loss: 0.0383 - val_accuracy: 0.9943


**PREDICTION**

In [ ]:
input_text=vectorizer('You freakin suck! i am going to hit you.')

In [ ]:
res=model.predict(np.expand_dims(input_text, axis=0))

1/1 [==============================] - 1s 835ms/step


In [ ]:
(res>0.5).astype(int)

array([[1, 0, 1, 0, 1, 0]])

In [ ]:
batch_x, batch_y = test.as_numpy_iterator().next()

In [ ]:
(model.predict(batch_x)>0.5).astype(int)

1/1 [==============================] - 0s 60ms/step


array([[1, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
res.shape

(1, 6)

In [ ]:
loss, Acc = model.evaluate(test)

print('Test Loss: ', loss)
print('Test Accuracy: ', Acc)

988/988 [==============================] - 47s 47ms/step - loss: 0.0366 - accuracy: 0.9949
Test Loss:  0.03663327917456627
Test Accuracy:  0.9948753714561462


In [ ]:
from keras.metrics import Precision, Recall, CategoricalAccuracy

pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

for batch in test.as_numpy_iterator():
    # unpack the batch
    X_test, y_test = batch
    # make a prediction
    y_pred = model.predict(X_test)

    y_test = y_test.flatten()
    y_pred = y_pred.flatten()

    pre.update_state(y_test, y_pred)
    re.update_state(y_test, y_pred)
    acc.update_state(y_test, y_pred)

1/1 [==============================] - 0s 59ms/step


In [ ]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

Precision: 0.8692810535430908, Recall:0.7017495036125183, Accuracy:0.49493926763534546
